name: Test Release

on:
  workflow_dispatch:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      # issues: write
      # pull-requests: write
      # packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install semantic-release
        run: |
          npm i -g semantic-release
          npm i -g @semantic-release/changelog
          npm i -g @semantic-release/git
          npm i -g @semantic-release/github
          npm i -g @semantic-release/exec
          npm i -g conventional-changelog-conventionalcommits

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: semantic-release
